const resolveApiBase = () => {
  const fromEnv = import.meta.env.VITE_API_URL;
  if (typeof window !== "undefined") {
    const protocol = window.location.protocol || "http:";
    const host = window.location.hostname || "localhost";
    if (fromEnv) {
      try {
        const parsed = new URL(fromEnv);
        const envHost = parsed.hostname || "";
        const currentIsLocal =
          host === "localhost" || host === "127.0.0.1";
        const envIsLocal =
          envHost === "localhost" || envHost === "127.0.0.1";
        if (!currentIsLocal && envIsLocal) {
          return `${protocol}//${host}:${parsed.port || "8080"}`;
        }
        return fromEnv;
      } catch {
        return fromEnv;
      }
    }
    return `${protocol}//${host}:8080`;
  }
  if (fromEnv) return fromEnv;
  return "http://localhost:8080";
};

const API_BASE = resolveApiBase();
const MARKETPLACE_REFRESH_KEY = "health_marketplace_requests_refresh";
const defaultProfileForm = (account = {}) => ({
  fullName: account.name || "",
  email: account.email || "",
  age: "",
  weightKg: "",
  heightCm: "",
  sex: "",
  conditions: "",
  allergies: "",
  region: "",
  phone: "",
  abhaNumber: "",
  abhaAddress: "",
  abhaStatus: "not_linked",
  aadhaarNo: "",
  maritalStatus: "",
  dateOfBirth: "",
  bloodGroup: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  country: "India",
  pinCode: "",
  emergencyContactName: "",
  emergencyContactPhone: "",
  registrationMode: "opd",
  visitTime: "OPD",
  unitDepartmentId: "",
  unitDoctorId: "",
});

const copy = {
  en: {
    brandTitle: "SehatSaathi",
    brandSubtitle: "India-first health guidance",
    navCreate: "Create account",
    navStart: "Start triage",
    navSignOut: "Sign out",
    heroEyebrow: "Made for Bharat-first care",
    heroTitle: "Fast, clear, and safe guidance for every home in India.",
    heroLead:
      "SehatSaathi collects symptoms, checks for red flags, and shares next-step guidance without replacing a clinician.",
    heroStart: "Start triage",
    heroHow: "How it works",
    heroNotice: "This is not a diagnosis. In emergencies, seek care immediately.",
    safetyTitle: "Safety first",
    safetySummary:
      "Create an account to save your profile and triage history.",
    safetySummaryAuthed: "Welcome back, {name}. Your guidance and history are saved securely.",
    pillOffline: "Offline friendly",
    pillPrivacy: "Privacy focused",
    pillBharat: "Bharat-ready",
    statTime: "Avg. triage time",
    statAccess: "Always available",
    statSave: "To save guidance",
    triageTitle: "Smart symptom triage",
    triageSubtitle: "Share symptoms and get safe guidance within minutes.",
    age: "Age",
    sex: "Sex",
    duration: "Duration (days)",
    severity: "Severity",
    commonSymptoms: "Common symptoms",
    additionalSymptoms: "Additional symptoms (comma separated)",
    additionalPlaceholder: "Example: stomach pain, rash",
    redFlags: "Red-flag symptoms",
    getGuidance: "Get guidance",
    runningTriage: "Running triage...",
    guidanceTitle: "Your guidance",
    guidanceEmpty:
      "Complete the triage form to see guidance here.",
    guidanceNote:
      "Guidance is not a diagnosis and does not replace a clinician.",
    account: "Account",
    patientPortal: "Patient login",
    doctorPortal: "Doctor login",
    continueAsDoctor: "Open doctor dashboard",
    doctorNoAccess: "Doctor access is not enabled for this account yet.",
    doctorSignupInfo: "Doctor account created. Admin approval is required before console access.",
    signIn: "Sign in",
    create: "Create",
    name: "Name",
    email: "Email",
    password: "Password",
    createAccount: "Create account",
    profileTitle: "Profile",
    profileSubtitle: "Save health context for more reliable guidance.",
    region: "Region or district",
    regionPlaceholder: "Example: Nashik, Maharashtra",
    conditions: "Chronic conditions (comma separated)",
    conditionsPlaceholder: "Example: diabetes, asthma",
    allergies: "Allergies (comma separated)",
    allergiesPlaceholder: "Example: penicillin, peanuts",
    saveProfile: "Save profile",
    historyTitle: "History",
    historyEmpty: "No triage history yet.",
    historySignIn: "Sign in to view your recent guidance.",
    historyShowMore: "Show full history",
    historyShowLess: "Show less",
    directoryTitle: "Doctor directory",
    directoryDesc:
      "We are building a verified list of local doctors, clinics, and community health workers. This will go live after validation.",
    directoryCard1: "Primary care clinics",
    directoryCard1Desc: "Search by district and speciality.",
    directoryCard2: "Community health workers",
    directoryCard2Desc: "Connect with trusted local health guides.",
    directoryCard3: "Tele-consult partners",
    directoryCard3Desc: "Book calls after triage when needed.",
    teleTitle: "Connect doctor",
    teleSubtitle: "Book remote consults and share follow-up updates from home.",
    teleMode: "Consult type",
    teleModeVideo: "Video",
    teleModeAudio: "Audio",
    teleModeChat: "Chat",
    teleConcern: "Primary concern",
    teleConcernPlaceholder: "Describe symptoms, context, and what help you need.",
    teleSlot: "Preferred slot",
    telePhone: "Phone for callback",
    teleBook: "Book teleconsult",
    teleStatus: "Status",
    teleEmpty: "No teleconsult requests yet.",
    teleOpenThread: "Open thread",
    teleThreadTitle: "Consult thread",
    teleMessagePlaceholder: "Share update for doctor...",
    teleSend: "Send update",
    teleLoading: "Loading teleconsults...",
    teleBooked: "Teleconsult request submitted.",
    teleError: "Unable to process teleconsult request.",
    teleStatusRequested: "Requested",
    teleStatusScheduled: "Scheduled",
    teleStatusInProgress: "In progress",
    teleStatusCompleted: "Completed",
    teleStatusCancelled: "Cancelled",
    careRequestType: "Visit type",
    careRequestInPerson: "In-person appointment",
    careRequestFeedTitle: "Your doctor requests",
    apptTitle: "Appointments",
    apptBook: "Book appointment",
    apptDepartment: "Department",
    apptReason: "Reason",
    apptDateTime: "Preferred date/time",
    apptEmpty: "No appointments yet.",
    encounterTitle: "Doctor clinical records",
    encounterEmpty: "No doctor records yet.",
    encounterOpen: "Open record",
    encounterDoctor: "Doctor",
    encounterDiagnosis: "Diagnosis",
    encounterPlan: "Plan",
    encounterVitals: "Vitals",
    encounterNotes: "Doctor notes",
    encounterPrescription: "Prescription",
    encounterOrders: "Orders",
    doctorChartTitle: "Doctor charting",
    doctorChartCreate: "Create encounter",
    chiefComplaint: "Chief complaint",
    findings: "Findings",
    diagnosisCode: "Diagnosis",
    diagnosisText: "Diagnosis",
    planText: "Care plan",
    followupDate: "Follow-up date",
    addNote: "Add signed note",
    signature: "Signature",
    noteText: "Note text",
    addPrescription: "Add prescription",
    medicines: "Medicines",
    addOrder: "Add order",
    orderType: "Order type",
    orderItem: "Order item",
    destination: "Destination",
    saveEncounter: "Save encounter",
    howTitle: "How it works",
    howBody:
      "1. Share symptoms in under 4 minutes. 2. AI triage checks for red flags and urgency. 3. Receive safe guidance and next steps.",
    designedTitle: "Designed for India",
    designedBody:
      "Works on low bandwidth, supports offline guidance, and keeps sensitive data private by default. More languages and local doctor partners will follow after validation.",
    complianceTitle: "Compliance",
    complianceBody:
      "This app provides general information, not diagnosis. It is built to align with Indian telemedicine guidance and safety standards.",
    trustTitle: "Why families trust SehatSaathi",
    trustCard1: "Clinician-reviewed guidance",
    trustCard1Desc: "Medical advisors review our triage rules and safety alerts.",
    trustCard2: "Transparent triage logic",
    trustCard2Desc: "We explain why we suggest home care or clinic visits.",
    trustCard3: "Privacy first",
    trustCard3Desc: "We do not sell data. You control what you share.",
    proofTitle: "Live usage dashboard",
    proofLiveNote: "Live numbers from your production database.",
    proofUsersLabel: "Registered users",
    proofTriageLabel: "Triage sessions",
    proofDoctorViewsLabel: "Doctor summary opens",
    howDecideTitle: "How we decide",
    howDecideBody:
      "We check severity, duration, age risk, and red-flag symptoms to suggest next steps. You always choose what to do next.",
    advisorTitle: "Medical advisors",
    advisorRole1: "Family physician (advisor)",
    advisorRole2: "Community health specialist (advisor)",
    advisorRole3: "Telemedicine consultant (advisor)",
    footer: "SehatSaathi • General guidance only • Built for web and iOS",
    disclaimerTitle: "Safety notice",
    disclaimerBody:
      "SehatSaathi provides general health guidance, not a medical diagnosis. If you have severe symptoms or an emergency, seek immediate care.",
    disclaimerConfirm:
      "By continuing, you confirm you understand this limitation.",
    disclaimerCta: "I understand, continue",
    langComing: "Gujarati",
    healthPassTitle: "Health pass for doctors",
    healthPassBody:
      "Generate a 30-minute share code so a doctor or clinic can view your profile and recent guidance.",
    generatePass: "Generate health pass",
    passCode: "Share code",
    passExpires: "Expires",
    passOpenDoctorView: "Open doctor view",
    passGenerating: "Generating...",
    passFailed: "Unable to generate pass.",
    triageSource: "Guidance source",
    sourceFallback: "Fallback rules",
    sourceLocalModel: "Local ML model",
    sourceGemini: "Gemini AI",
    sourceOpenai: "OpenAI",
    doctorViewTitle: "Doctor summary view",
    doctorViewLoading: "Loading patient summary...",
    doctorViewExpired: "This health pass is invalid or expired.",
    doctorViewPatient: "Patient",
    doctorViewProfile: "Profile",
    doctorViewRecent: "Recent guidance",
    doctorSymptoms: "Symptoms",
    doctorSeverity: "Severity",
    doctorDuration: "Duration",
    doctorRedFlags: "Red flags",
    doctorSource: "Source",
    doctorNone: "None",
    doctorDays: "days",
    doctorRatePrompt: "Was this summary useful?",
    doctorRateUseful: "Useful",
    doctorRateNotUseful: "Not useful",
    doctorRateSaved: "Doctor rating saved.",
    feedbackPrompt: "Did this guidance help your decision?",
    feedbackYes: "Yes, helpful",
    feedbackNo: "No, not helpful",
    followupPrompt: "Did a clinic or doctor visit happen after this?",
    followupYes: "Yes, visit happened",
    followupNo: "No, not yet",
    feedbackSaved: "Feedback saved.",
    memberTitle: "Care command center",
    memberSubtitle: "Your fast controls for triage, doctor sharing, and health records.",
    memberCardProfile: "Profile completion",
    memberCardLast: "Last guidance",
    memberCardPass: "Doctor share pass",
    memberCardRecords: "Medical records",
    memberOpenProfile: "Open profile",
    memberOpenHistory: "Open history",
    memberOpenPass: "Generate pass",
    memberUploadDocs: "Upload reports",
    memberNoTriage: "No triage yet",
    chatTitle: "SehatSaathi Assistant",
    chatOpen: "Chat",
    chatPlaceholder: "Type your question...",
    chatSend: "Send",
    chatThinking: "Thinking...",
    chatGreeting: "Hi, I can help with symptoms, triage steps, and what to do before clinic visits.",
    familyTitle: "Family profiles",
    addMember: "Add member",
    relation: "Relation",
    bloodType: "Blood type",
    saveMember: "Save member",
    recordsTitle: "Medical records",
    uploadRecord: "Upload report (PDF/Image)",
    emergencyCard: "Emergency card",
    generateEmergencyCard: "Generate emergency card",
    openEmergencyCard: "Open emergency card",
    shareHistory: "Share history",
    downloadVisitPdf: "Download visit summary PDF",
    clinicTitle: "Clinic starter page",
    doctorConsoleTitle: "Doctor dashboard",
    doctorConsoleSubtitle: "Manage remote consult requests and respond to patients.",
    doctorConsoleSignIn: "Doctor/admin sign in required.",
    doctorConsoleNoAccess: "Your account does not have doctor access.",
    doctorConsoleUpdate: "Update consult",
    doctorConsoleMeetingUrl: "Meeting URL",
    doctorConsoleSave: "Save status",
    doctorConsoleSaved: "Consult status updated.",
    doctorConsoleOpen: "Open doctor dashboard",
    clinicCodePlaceholder: "Enter 6-digit code",
    clinicOpen: "Open patient summary",
    doctorLanguage: "Doctor language",
    qrReady: "QR ready",
    oneTimeCodeNote: "Code is one-time and expires in 30 minutes.",
    clinicScanStart: "Start QR scan",
    clinicScanStop: "Stop QR scan",
    clinicScanUnsupported: "QR camera scan is not supported on this browser. Use code entry.",
    clinicScannerActive: "Scanner active. Point camera at SehatSaathi QR.",
    clinicScanInvalid: "QR scanned, but no valid share code found.",
    doctorDownloadRecord: "Download record",
    removePhoto: "Remove photo",
    removeRecord: "Delete",
    triageModeGeneral: "General",
    triageModeDental: "Dental",
    dentalSymptoms: "Dental symptoms",
    dentalPainScale: "Dental pain scale (1-10)",
    dentalHotColdTrigger: "Pain triggered by hot/cold",
    dentalSwelling: "Visible facial/gum swelling",
    dentalRedFlags: "Dental red flags",
  },
  gu: {
    brandTitle: "સેહતસાથી",
    brandSubtitle: "ભારત માટે આરોગ્ય માર્ગદર્શન",
    navCreate: "એકાઉન્ટ બનાવો",
    navStart: "ટ્રાયેજ શરૂ કરો",
    navSignOut: "સાઇન આઉટ",
    heroEyebrow: "ભારત-ફર્સ્ટ કાળજી માટે બનાવેલ",
    heroTitle: "ભારતના દરેક ઘરમાં ઝડપી, સ્પષ્ટ અને સુરક્ષિત માર્ગદર્શન.",
    heroLead:
      "સેહતસાથી લક્ષણો એકત્ર કરે છે, રેડ ફ્લેગ ચેક કરે છે અને ડૉક્ટરને બદલી્યા વગર આગળ શું કરવું તે જણાવે છે.",
    heroStart: "ટ્રાયેજ શરૂ કરો",
    heroHow: "કેવી રીતે કામ કરે છે",
    heroNotice:
      "આ નિદાન નથી. ઇમર્જન્સીમાં તરત સારવાર લો.",
    safetyTitle: "સેફટી પ્રથમ",
    safetySummary:
      "તમારો પ્રોફાઇલ અને ટ્રાયેજ ઇતિહાસ સાચવવા એકાઉન્ટ બનાવો.",
    safetySummaryAuthed:
      "પાછા સ્વાગત, {name}. તમારું માર્ગદર્શન અને ઇતિહાસ સુરક્ષિત રીતે સાચવાયું છે.",
    pillOffline: "ઓફલાઇન-ફ્રેન્ડલી",
    pillPrivacy: "પ્રાઇવસી ફોકસ",
    pillBharat: "ભારત-રેડી",
    statTime: "સરેરાશ ટ્રાયેજ સમય",
    statAccess: "હંમેશા ઉપલબ્ધ",
    statSave: "માર્ગદર્શન સાચવવા",
    triageTitle: "સ્માર્ટ સિમ્પ્ટમ ટ્રાયેજ",
    triageSubtitle: "લક્ષણો શેર કરો અને મિનિટોમાં સુરક્ષિત માર્ગદર્શન મેળવો.",
    age: "વય",
    sex: "લિંગ",
    duration: "સમયગાળો (દિવસ)",
    severity: "તીવ્રતા",
    commonSymptoms: "સામાન્ય લક્ષણો",
    additionalSymptoms: "વધારાના લક્ષણો (કૉમા દ્વારા અલગ કરો)",
    additionalPlaceholder: "ઉદાહરણ: પેટમાં દુખાવો, ચામડી પર ચક્કા",
    redFlags: "રેડ-ફ્લેગ લક્ષણો",
    getGuidance: "માર્ગદર્શન મેળવો",
    runningTriage: "ટ્રાયેજ ચાલી રહ્યું છે...",
    guidanceTitle: "તમારું માર્ગદર્શન",
    guidanceEmpty: "માર્ગદર્શન જોવા માટે ટ્રાયેજ ફોર્મ ભરો.",
    guidanceNote:
      "આ નિદાન નથી અને ડૉક્ટરને બદલે નહીં.",
    account: "એકાઉન્ટ",
    patientPortal: "પેશન્ટ લોગિન",
    doctorPortal: "ડૉક્ટર લોગિન",
    continueAsDoctor: "ડૉક્ટર ડેશબોર્ડ ખોલો",
    doctorNoAccess: "આ એકાઉન્ટ માટે ડૉક્ટર ઍક્સેસ હજુ સક્રિય નથી.",
    doctorSignupInfo: "ડૉક્ટર એકાઉન્ટ બનાવાયું. કન્સોલ ઍક્સેસ માટે એડમિન મંજૂરી જરૂરી છે.",
    signIn: "સાઇન ઇન",
    create: "બનાવો",
    name: "નામ",
    email: "ઈમેલ",
    password: "પાસવર્ડ",
    createAccount: "એકાઉન્ટ બનાવો",
    profileTitle: "પ્રોફાઇલ",
    profileSubtitle: "વધુ વિશ્વસનીય માર્ગદર્શન માટે આરોગ્ય માહિતી સાચવો.",
    region: "પ્રદેશ અથવા જિલ્લા",
    regionPlaceholder: "ઉદાહરણ: રાજકોટ, ગુજરાત",
    conditions: "દીર્ઘકાળીન બીમારીઓ (કૉમા દ્વારા)",
    conditionsPlaceholder: "ઉદાહરણ: ડાયાબિટીસ, અસ્થમા",
    allergies: "એલર્જી (કૉમા દ્વારા)",
    allergiesPlaceholder: "ઉદાહરણ: પેનિસિલિન, મગફળી",
    saveProfile: "પ્રોફાઇલ સાચવો",
    historyTitle: "ઇતિહાસ",
    historyEmpty: "હજુ ટ્રાયેજ ઇતિહાસ નથી.",
    historySignIn: "તાજેતરનું માર્ગદર્શન જોવા સાઇન ઇન કરો.",
    historyShowMore: "પૂર્ણ ઇતિહાસ જુઓ",
    historyShowLess: "ઓછું બતાવો",
    directoryTitle: "ડૉક્ટર ડિરેક્ટરી",
    directoryDesc:
      "અમે સ્થાનિક ડૉક્ટરો, ક્લિનિક્સ અને સમુદાય આરોગ્ય કર્મીઓની ચકાસેલી સૂચિ બનાવી રહ્યા છીએ.",
    directoryCard1: "પ્રાથમિક કાળજી ક્લિનિક્સ",
    directoryCard1Desc: "જિલ્લા અને સ્પેશિયલિટી મુજબ શોધો.",
    directoryCard2: "સમુદાય આરોગ્ય કર્મીઓ",
    directoryCard2Desc: "વિશ્વસનીય સ્થાનિક આરોગ્ય માર્ગદર્શકો જોડાવો.",
    directoryCard3: "ટેલિ-કન્સલ્ટ પાર્ટનર્સ",
    directoryCard3Desc: "જરૂર પડે ત્યારે કોલ બુક કરો.",
    teleTitle: "ઘરેથી ડૉક્ટર કનેક્ટ",
    teleSubtitle: "ઘરે બેઠા ટેલિકન્સલ્ટ બુક કરો અને ફોલો-અપ અપડેટ મોકલો.",
    teleMode: "કન્સલ્ટ પ્રકાર",
    teleModeVideo: "વિડિયો",
    teleModeAudio: "ઑડિયો",
    teleModeChat: "ચેટ",
    teleConcern: "મુખ્ય સમસ્યા",
    teleConcernPlaceholder: "લક્ષણો અને જરૂરી મદદ ટૂંકમાં લખો.",
    teleSlot: "પસંદીદા સમય",
    telePhone: "કૉલબેક ફોન",
    teleBook: "ટેલિકન્સલ્ટ બુક કરો",
    teleStatus: "સ્થિતિ",
    teleEmpty: "હજુ સુધી ટેલિકન્સલ્ટ વિનંતી નથી.",
    teleOpenThread: "થ્રેડ ખોલો",
    teleThreadTitle: "કન્સલ્ટ થ્રેડ",
    teleMessagePlaceholder: "ડૉક્ટર માટે અપડેટ લખો...",
    teleSend: "મોકલો",
    teleLoading: "ટેલિકન્સલ્ટ લોડ થઈ રહ્યું છે...",
    teleBooked: "ટેલિકન્સલ્ટ વિનંતી મોકલાઈ.",
    teleError: "ટેલિકન્સલ્ટ વિનંતી પ્રક્રિયા થઈ શકી નહીં.",
    teleStatusRequested: "વિનંતી મોકલાઈ",
    teleStatusScheduled: "શેડ્યૂલ",
    teleStatusInProgress: "ચાલુ",
    teleStatusCompleted: "પૂર્ણ",
    teleStatusCancelled: "રદ",
    careRequestType: "વિઝિટ પ્રકાર",
    careRequestInPerson: "સામે-સામે અપોઇન્ટમેન્ટ",
    careRequestFeedTitle: "તમારી ડૉક્ટર વિનંતીઓ",
    howTitle: "કેવી રીતે કામ કરે છે",
    howBody:
      "1. 4 મિનિટમાં લક્ષણો શેર કરો. 2. ટ્રાયેજ રેડ ફ્લેગ અને તાત્કાલિકતા ચેક કરે છે. 3. સુરક્ષિત માર્ગદર્શન મેળવો.",
    designedTitle: "ભારત માટે ડિઝાઇન",
    designedBody:
      "લો બૅન્ડવિડ્થ પર ચાલે છે, ઓફલાઇન માર્ગદર્શન સપોર્ટ કરે છે અને ડેટા પ્રાઇવસી રાખે છે.",
    complianceTitle: "કમ્પ્લાયન્સ",
    complianceBody:
      "આ એપ સામાન્ય માહિતી આપે છે, નિદાન નથી. તે ભારતીય ટેલિમેડિસિન માર્ગદર્શિકા સાથે સુસંગત છે.",
    trustTitle: "પરિવારો કેમ વિશ્વાસ કરે છે",
    trustCard1: "ક્લિનિશિયન સમીક્ષિત માર્ગદર્શન",
    trustCard1Desc: "અમારા ટ્રાયેજ નિયમો અને સેફટી એલર્ટ ડૉક્ટરો ચકાસે છે.",
    trustCard2: "પારદર્શક ટ્રાયેજ લોજિક",
    trustCard2Desc: "અમે ઘરે સંભાળ કે ક્લિનિક ભલામણ કેમ કરીએ તે જણાવીએ છીએ.",
    trustCard3: "પ્રાઇવસી પ્રથમ",
    trustCard3Desc: "અમે ડેટા વેચતા નથી. તમે શું શેર કરવું તે તમે નક્કી કરો.",
    proofTitle: "લાઇવ યુઝેજ ડેશબોર્ડ",
    proofLiveNote: "તમારા પ્રોડક્શન ડેટાબેઝમાંથી લાઇવ આંકડા.",
    proofUsersLabel: "રજિસ્ટર્ડ યુઝર્સ",
    proofTriageLabel: "ટ્રાયેજ સેશન્સ",
    proofDoctorViewsLabel: "ડૉક્ટર સમરી ઓપન",
    howDecideTitle: "અમે કેવી રીતે નક્કી કરીએ",
    howDecideBody:
      "અમે તીવ્રતા, સમયગાળો, વય જોખમ અને રેડ-ફ્લેગ લક્ષણો તપાસી આગળ શું કરવું તે સૂચવીએ છીએ.",
    advisorTitle: "મેડિકલ એડવાઇઝર્સ",
    advisorRole1: "ફેમિલી ફિઝિશિયન (એડવાઇઝર)",
    advisorRole2: "કોમ્યુનિટી હેલ્થ સ્પેશ્યાલિસ્ટ (એડવાઇઝર)",
    advisorRole3: "ટેલિમેડિસિન કન્સલ્ટન્ટ (એડવાઇઝર)",
    footer: "સેહતસાથી • સામાન્ય માર્ગદર્શન માત્ર • વેબ અને iOS માટે બનાવેલ",
    disclaimerTitle: "સેફટી સૂચના",
    disclaimerBody:
      "સેહતસાથી સામાન્ય આરોગ્ય માર્ગદર્શન આપે છે, નિદાન નથી. ગંભીર લક્ષણો હોય તો તરત સારવાર લો.",
    disclaimerConfirm:
      "આગળ વધતાં તમે આ મર્યાદા સમજો છો તે સ્વીકારો છો.",
    disclaimerCta: "હું સમજ્યો, આગળ વધો",
    langComing: "ગુજરાતી",
    healthPassTitle: "ડૉક્ટર માટે હેલ્થ પાસ",
    healthPassBody:
      "30 મિનિટ માટે શેર કોડ બનાવો જેથી ડૉક્ટર અથવા ક્લિનિક તમારી પ્રોફાઇલ અને તાજેતરનું માર્ગદર્શન જોઈ શકે.",
    generatePass: "હેલ્થ પાસ બનાવો",
    passCode: "શેર કોડ",
    passExpires: "સમાપ્તિ સમય",
    passOpenDoctorView: "ડૉક્ટર વ્યૂ ખોલો",
    passGenerating: "બનાવી રહ્યું છે...",
    passFailed: "હેલ્થ પાસ બનાવી શકાયો નહીં.",
    triageSource: "માર્ગદર્શન સ્ત્રોત",
    sourceFallback: "ફોલબેક નિયમો",
    sourceLocalModel: "લોકલ ML મોડલ",
    sourceGemini: "Gemini AI",
    sourceOpenai: "OpenAI",
    doctorViewTitle: "ડૉક્ટર સમરી વ્યૂ",
    doctorViewLoading: "પેશન્ટ સમરી લોડ થઈ રહી છે...",
    doctorViewExpired: "આ હેલ્થ પાસ અમાન્ય છે અથવા સમાપ્ત થયો છે.",
    doctorViewPatient: "પેશન્ટ",
    doctorViewProfile: "પ્રોફાઇલ",
    doctorViewRecent: "તાજેતરનું માર્ગદર્શન",
    doctorSymptoms: "લક્ષણો",
    doctorSeverity: "તીવ્રતા",
    doctorDuration: "સમયગાળો",
    doctorRedFlags: "રેડ ફ્લેગ્સ",
    doctorSource: "સ્ત્રોત",
    doctorNone: "નથી",
    doctorDays: "દિવસ",
    doctorRatePrompt: "આ સમરી ઉપયોગી હતી?",
    doctorRateUseful: "ઉપયોગી",
    doctorRateNotUseful: "ઉપયોગી નહોતી",
    doctorRateSaved: "ડૉક્ટર રેટિંગ સેવ થયું.",
    feedbackPrompt: "આ માર્ગદર્શનથી નિર્ણયમાં મદદ મળી?",
    feedbackYes: "હા, મદદ મળી",
    feedbackNo: "ના, મદદ મળી નહીં",
    followupPrompt: "પછી ક્લિનિક/ડૉક્ટર મુલાકાત થઈ?",
    followupYes: "હા, મુલાકાત થઈ",
    followupNo: "ના, હજુ નહીં",
    feedbackSaved: "ફીડબેક સેવ થયું.",
    memberTitle: "કેર કમાન્ડ સેન્ટર",
    memberSubtitle: "ટ્રાયેજ, ડૉક્ટર શેરિંગ અને હેલ્થ રેકોર્ડ્સ માટે ઝડપી નિયંત્રણો.",
    memberCardProfile: "પ્રોફાઇલ પૂર્ણતા",
    memberCardLast: "છેલ્લું માર્ગદર્શન",
    memberCardPass: "ડૉક્ટર શેર પાસ",
    memberCardRecords: "મેડિકલ રેકોર્ડ્સ",
    memberOpenProfile: "પ્રોફાઇલ ખોલો",
    memberOpenHistory: "ઇતિહાસ ખોલો",
    memberOpenPass: "પાસ બનાવો",
    memberUploadDocs: "જલ્દી અપલોડ",
    memberNoTriage: "હજુ ટ્રાયેજ નથી",
    chatTitle: "સેહતસાથી સહાયક",
    chatOpen: "ચેટ",
    chatPlaceholder: "તમારો પ્રશ્ન લખો...",
    chatSend: "મોકલો",
    chatThinking: "જવાબ તૈયાર થઈ રહ્યો છે...",
    chatGreeting: "નમસ્તે, હું લક્ષણો, ટ્રાયેજ પગલાં અને ક્લિનિક મુલાકાત પહેલા શું કરવું તેમાં મદદ કરી શકું છું.",
    familyTitle: "કુટુંબ પ્રોફાઇલ્સ",
    addMember: "સભ્ય ઉમેરો",
    relation: "સંબંધ",
    bloodType: "બ્લડ ગ્રુપ",
    saveMember: "સભ્ય સેવ કરો",
    recordsTitle: "મેડિકલ રેકોર્ડ્સ",
    uploadRecord: "રિપોર્ટ અપલોડ કરો (PDF/Image)",
    emergencyCard: "ઇમરજન્સી કાર્ડ",
    generateEmergencyCard: "ઇમરજન્સી કાર્ડ બનાવો",
    openEmergencyCard: "ઇમરજન્સી કાર્ડ ખોલો",
    shareHistory: "શેર ઇતિહાસ",
    downloadVisitPdf: "વિઝિટ સમરી PDF ડાઉનલોડ કરો",
    clinicTitle: "ક્લિનિક સ્ટાર્ટર પેજ",
    doctorConsoleTitle: "ડૉક્ટર ડેશબોર્ડ",
    doctorConsoleSubtitle: "રિમોટ કન્સલ્ટ વિનંતીઓ મેનેજ કરો અને દર્દીને જવાબ આપો.",
    doctorConsoleSignIn: "ડૉક્ટર/એડમિન સાઇન ઇન જરૂરી.",
    doctorConsoleNoAccess: "તમારા એકાઉન્ટ પાસે ડૉક્ટર ઍક્સેસ નથી.",
    doctorConsoleUpdate: "કન્સલ્ટ અપડેટ",
    doctorConsoleMeetingUrl: "મીટિંગ URL",
    doctorConsoleSave: "સ્થિતિ સાચવો",
    doctorConsoleSaved: "કન્સલ્ટ સ્થિતિ અપડેટ થઈ.",
    doctorConsoleOpen: "ડૉક્ટર ડેશબોર્ડ ખોલો",
    clinicCodePlaceholder: "6-અંક કોડ દાખલ કરો",
    clinicOpen: "પેશન્ટ સમરી ખોલો",
    doctorLanguage: "ડૉક્ટર ભાષા",
    qrReady: "QR તૈયાર",
    oneTimeCodeNote: "કોડ એક વખત માટે છે અને 30 મિનિટમાં સમાપ્ત થાય છે.",
    clinicScanStart: "QR સ્કેન શરૂ કરો",
    clinicScanStop: "QR સ્કેન બંધ કરો",
    clinicScanUnsupported: "આ બ્રાઉઝરમાં QR કેમેરા સ્કેન સપોર્ટેડ નથી. કોડ દાખલ કરો.",
    clinicScannerActive: "સ્કેનર ચાલુ છે. કેમેરા QR પર લાવો.",
    clinicScanInvalid: "QR વાંચાયું, પરંતુ માન્ય શેર કોડ મળ્યો નથી.",
    doctorDownloadRecord: "રેકોર્ડ ડાઉનલોડ કરો",
    removePhoto: "ફોટો દૂર કરો",
    removeRecord: "ડિલીટ",
    triageModeGeneral: "જનરલ",
    triageModeDental: "ડેન્ટલ",
    dentalSymptoms: "ડેન્ટલ લક્ષણો",
    dentalPainScale: "ડેન્ટલ પેઇન સ્કેલ (1-10)",
    dentalHotColdTrigger: "ગરમ/ઠંડાથી દુખાવો વધે છે",
    dentalSwelling: "ચહેરા/મસૂડામાં સોજો દેખાય છે",
    dentalRedFlags: "ડેન્ટલ રેડ ફ્લેગ્સ",
  },
};

const commonSymptoms = [
  "Fever",
  "Cough",
  "Sore throat",
  "Headache",
  "Body ache",
  "Fatigue",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Dizziness",
];

const redFlagOptions = [
  "Chest pain",
  "Trouble breathing",
  "Uncontrolled bleeding",
  "Loss of consciousness",
  "Seizure",
  "Severe allergic reaction",
  "Stroke-like symptoms",
  "Suicidal thoughts",
];

const dentalSymptomsOptions = [
  "Tooth pain",
  "Gum swelling",
  "Bleeding gums",
  "Tooth sensitivity",
  "Broken tooth",
  "Wisdom tooth pain",
  "Mouth ulcer",
  "Bad breath",
  "Jaw pain",
];

const dentalRedFlagOptions = [
  "Facial swelling with fever",
  "Difficulty swallowing",
  "Difficulty breathing",
  "Uncontrolled oral bleeding",
  "Trauma with severe bleeding",
];

const symptomTranslations = {
  gu: {
    Fever: "તાવ",
    Cough: "ખાંસી",
    "Sore throat": "ગળામાં દુખાવો",
    Headache: "માથાનો દુખાવો",
    "Body ache": "શરીરમાં દુખાવો",
    Fatigue: "થાક",
    Nausea: "મતલાબ",
    Vomiting: "ઉલટી",
    Diarrhea: "દસ્ત",
    Dizziness: "ચક્કર",
    "Chest pain": "છાતીમાં દુખાવો",
    "Trouble breathing": "શ્વાસ લેવામાં મુશ્કેલી",
    "Uncontrolled bleeding": "નિયંત્રણ વગરનું રક્તસ્ત્રાવ",
    "Loss of consciousness": "બેભાન થવું",
    Seizure: "ઝટકા",
    "Severe allergic reaction": "ગંભીર એલર્જીક પ્રતિક્રિયા",
    "Stroke-like symptoms": "સ્ટ્રોક જેવા લક્ષણો",
    "Suicidal thoughts": "આપઘાતી વિચારો",
  },
};

const fallbackTriage = (payload = {}) => {
  payload = payload || {};
  const severity = Number(payload.severity || 3);
  const durationDays = Number(payload.durationDays || 1);
  const redFlags = payload.redFlags || [];
  const hasRedFlags = redFlags.length > 0;

  if (hasRedFlags) {
    return {
      level: "emergency",
      headline: "Seek emergency care now",
      urgency: "Go to the nearest emergency facility or call local emergency services.",
      suggestions: ["Do not delay.", "Ask someone to help you reach care quickly."],
      disclaimer:
        "This is general guidance, not a medical diagnosis. For emergencies, seek immediate care.",
    };
  }

  if (severity >= 4 || durationDays >= 7) {
    return {
      level: "urgent",
      headline: "Talk to a clinician soon",
      urgency: "Consider a local clinic visit within 24-48 hours.",
      suggestions: [
        "Track symptoms over the next 24 hours.",
        "Hydrate and rest.",
        "Seek care if symptoms worsen.",
      ],
      disclaimer:
        "This is general guidance, not a medical diagnosis. For emergencies, seek immediate care.",
    };
  }

  return {
    level: "self_care",
    headline: "Likely manageable with home care",
    urgency: "Monitor symptoms and practice self-care.",
    suggestions: ["Rest, hydrate, and avoid strenuous activity."],
    disclaimer:
      "This is general guidance, not a medical diagnosis. For emergencies, seek immediate care.",
  };
};

export {
  resolveApiBase,
  MARKETPLACE_REFRESH_KEY,
  defaultProfileForm,
  copy,
  commonSymptoms,
  redFlagOptions,
  dentalSymptomsOptions,
  dentalRedFlagOptions,
  symptomTranslations,
  fallbackTriage,
};
